Use mktemp for temp file creation. Move log_msg to allow reporting mktemp errors. Disable exit err_exit in print to prevent false error reporting.

diff --git a/lpf_gs b/lpf_gs
--- a/lpf_gs
+++ b/lpf_gs
@@ -90,13 +90,40 @@
 # lpd(8) tries 3 times and aborts if it doesn't receive 0 or 2.
 #
 
-# setup
 __basename="lpf_gs"
-__progname=$(basename $0)
-gs_device=$(basename ${__progname} '.if' | cut -d '_' -f 2)
-pid=$$
+__progname=$(basename "$0")
+__dirname=$(dirname "$0")
 hostname=$(hostname -s)
-tmpfile=/tmp/$gs_device.$pid.$RANDOM
+pid=$$
+err_exit=1
+gs_device=$(basename "$__progname" '.if' | cut -d '_' -f 2)
+function log_msg {
+	msg="$@"
+	if [ ! -t 0 ] ; then
+	  if [ "${msg:-empty}" != "empty" ] ; then
+	    # sane date format but different from lpd
+	    # date=$(date "+%Y-%m-%d %H:%M:%S")
+
+	    # format date like lpd
+	    date=$(date "+%b %e %H:%M:%S")
+
+	    # send to stderr for logging
+	    # lpd will handle logging
+	    echo "$date $hostname $__progname[$pid]: ($job) $msg" >&2
+	  fi
+	else
+		# send to stdout to work with pipes
+		# when users call from cl
+		echo $msg
+	fi
+}
+
+# create temp file
+TMPFILE=`mktemp -q /tmp/$gs_device.XXXXXXXXXX` ||
+  (log_msg "Unable to create tmp file ... aborting" ; exit 1)
+
+trap "rm -f '${TMPFILE}'" EXIT
+trap "log_msg $__progname aborted by user;exit $err_exit" INT
 
 # command line parameters that will be passed in from lpd
 # printcap(5) FILTERS section
@@ -115,37 +142,14 @@ FALSE=1
 call="$0 $@"
 cmd="print"	  # options: abort | print | usage | version
 debug=$FALSE
-exit_err=1
 gs=$(which gs)
 version="1.0"
-
-function log_msg {
-	msg="$@"
-	if [ ! -t 0 ] ; then
-	  if [ "${msg:-empty}" != "empty" ] ; then
-	    # sane date format but different from lpd
-	    # date=$(date "+%Y-%m-%d %H:%M:%S")
-
-	    # format date like lpd
-	    date=$(date "+%b %e %H:%M:%S")
-
-	    # send to stderr for logging
-	    # lpd will handle logging
-	    echo "$date $hostname ${__progname}[$pid]: ($job) $msg" >&2
-	  fi
-	else
-		# send to stdout to work with pipes
-		# when users call from cl
-		echo $msg
-	fi
-}
 
 # does the real work
 function print {
 	# send stdin to a file we can test format for
-	cat > $tmpfile
-	ft=$(file -b $tmpfile | cut -d ' ' -f 1)
-	gs_in_file=$tmpfile
+	cat > "${TMPFILE}"
+	ft=$(file -b "${TMPFILE}" | cut -d ' ' -f 1)
 	can_convert=$TRUE
 	case $ft in
 		ASCII)
@@ -165,13 +169,13 @@ function print {
 
 	if [ ${can_convert} -eq $TRUE ] ; then
 	  if [ "${af:-empty}" != "empty" ] ; then
-	    npages=$($gs -q -dNODISPLAY -c "($tmpfile) (r) file runpdfbegin pdfpagecount = quit")
+	    npages=$($gs -q -dNODISPLAY -c "(${TMPFILE}) (r) file runpdfbegin pdfpagecount = quit")
 	    printf "%7.2f\t%s:%s\n" "$npages" "$host" "$name" >> $af
 	  fi
 
-	  $gs -q -dNOPROMPT -dNOPAUSE -dSAFER -dBATCH -dNOPAUSE -sDEVICE=$gs_device -sOutputFile=- $tmpfile -c quit
+	  $gs -q -dNOPROMPT -dNOPAUSE -dSAFER -dBATCH -dNOPAUSE -sDEVICE=$gs_device -sOutputFile=- $TMPFILE -c quit
 	fi
-	exit $err_exit
+#	exit $err_exit
 }
 
 function version {
@@ -209,10 +213,6 @@ function debug {
 	  log_msg
 	fi
 }
-
-trap "rm -f ${tmpfile}" EXIT
-
-trap "log_msg ${__progname} aborted by user;rm -f ${tmpfile};exit" INT
 
 has_gs_device=$(gs -h | grep $gs_device | wc -l)
 if [ $has_gs_device -eq 0 ] ; then
