Add error logging for a2ps and enscript.

diff --git a/lpf_gs b/lpf_gs
--- a/lpf_gs
+++ b/lpf_gs
@@ -121,12 +121,14 @@ function log_msg {
 # create temp files
 TMPFILE=`mktemp -q /tmp/$gs_device.XXXXXXXXXX` ||
 	(log_msg "Unable to create tmp file ... aborting" ; exit 1)
+ASERRFILE=`mktemp /tmp/$gs_device.as_err.XXXXXX` ||
+	(log_msg "Unable to create ghostscript tmp file ... aborting" ; exit 1)
 ASTMPFILE=`mktemp /tmp/$gs_device.as.XXXXXX` ||
 	(log_msg "Unable to create ghostscript tmp file ... aborting" ; exit 1)
-GSTMPFILE=`mktemp /tmp/$gs_device.gs.XXXXXX` ||
+GSERRFILE=`mktemp /tmp/$gs_device.gs_err.XXXXXX` ||
 	(log_msg "Unable to create ghostscript tmp file ... aborting" ; exit 1)
 
-trap "rm -f '${TMPFILE}' '${ASTMPFILE}' '${GSTMPFILE}'" EXIT
+trap "rm -f '${TMPFILE}' '${ASERRFILE}' '${ASTMPFILE}' '${GSERRFILE}'" EXIT
 trap "log_msg $__progname aborted by user;exit $err_exit" INT
 
 # command line parameters that will be passed in from lpd
@@ -146,7 +148,7 @@ FALSE=1
 call="$0 $@"
 cmd="print"	  # options: abort | print | usage | version
 debug=$FALSE
-as=$(which a2ps 2>/dev/null || which  enscript 2>/dev/null)
+as=$(which a2ps 2>/dev/null || which enscript 2>/dev/null)
 gs=$(which gs 2>/dev/null)
 version="1.0"
 
@@ -160,19 +162,26 @@ function print {
 	if [ "$(echo $ft | grep text)" ] ; then
 		__as=$(basename "$as")
 		if [  "$__as" = "a2ps" ] ; then
-			log_msg Converting from ASCII to ps using a2ps
+			log_msg Converting from ASCII to postscript using $__as
 			__header="-B --center-title='${job}'"
-			$as -M letter $__header --output="${ASTMPFILE}" "${TMPFILE}"
-			mv "${ASTMPFILE}" "${TMPFILE}"
+			$as -M letter $__header --output="${ASTMPFILE}" "${TMPFILE}" \
+			    2>"${ASERRFILE}"
+			as_success=$?
 		elif [ "$__as" = "enscript" ] ; then
 			__header="${job} %W Page $% of $="
-			log_msg Converting from ASCII to ps using enscript
-			log_msg $as --header="$__header" --output="${ASTMPFILE}" "${TMPFILE}"
-			$as --header="$__header" --output="${ASTMPFILE}" "${TMPFILE}"
-			mv "${ASTMPFILE}" "${TMPFILE}"
+			log_msg Converting from ASCII to postscript using $__as
+			$as -q --header="$__header" --output="${ASTMPFILE}" "${TMPFILE}" \
+			    2>"${ASERRFILE}"
+			as_success=$?
 		else
 			can_convert=$FALSE
 			log_msg ASCII, abort conversion...
+		fi
+		if [ $as_success -eq $FALSE ] ; then
+			log_msg $(cat "${ASERRFILE}")
+			exit $as_success
+		else
+			mv "${ASTMPFILE}" "${TMPFILE}"
 		fi
 	elif [ "$(echo $ft | egrep 'PDF|PostScript')" ] ; then
 		log_msg Converting from PDF to $gs_device
@@ -193,16 +202,16 @@ function print {
 			gs_init="${__dirname}/gs_init.ps"
 			$gs -q -dNOPROMPT -dNOPAUSE -dSAFER -dBATCH -dNOPAUSE \
 			    -sDEVICE=${gs_device} -sOutputFile=- "${gs_init}" \
-			    "${TMPFILE}" -c quit 2>"${GSTMPFILE}"
+			    "${TMPFILE}" -c quit 2>"${GSERRFILE}"
 			gs_success=${?}
 		else
 			$gs -q -dNOPROMPT -dNOPAUSE -dSAFER -dBATCH -dNOPAUSE \
 			    -sDEVICE=${gs_device} -sOutputFile=- "${TMPFILE}" -c quit \
-			    2>"${GSTMPFILE}"
+			    2>"${GSERRFILE}"
 			gs_success=${?}
 		fi
-		log_msg $(cat "${GSTMPFILE}")
-		rm "${GSTMPFILE}"
+		log_msg $(cat "${GSERRFILE}")
+		rm "${GSERRFILE}"
 	fi
 	exit $gs_success
 }
